# Generated by Django 2.1.2 on 2018-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='emailcontacto',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
